/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'equipment' : null } |
  { 'bbGun' : null };
export interface Cell { 'value' : Value, 'name' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Listing {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'seller' : Principal,
  'sellerName' : string,
  'updatedAt' : bigint,
  'category' : Category,
  'price' : bigint,
  'images' : Array<string>,
}
export type ListingError = { 'notAuthorized' : null } |
  { 'notFound' : bigint };
export type Result = { 'ok' : Listing } |
  { 'err' : ListingError };
export type Result_1 = { 'ok' : null } |
  { 'err' : ListingError };
export type Result_2 = { 'ok' : null } |
  { 'err' : Error };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface SellerContact { 'seller' : Principal, 'sellerName' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_2>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createListing' : ActorMethod<
    [string, Category, bigint, string, Array<string>, string],
    Result
  >,
  'deleteListing' : ActorMethod<[bigint], Result_1>,
  'execute' : ActorMethod<[string], Result__1>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getListing' : ActorMethod<[bigint], [] | [Listing]>,
  'getSellerContact' : ActorMethod<[bigint], [] | [SellerContact]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listListings' : ActorMethod<
    [[] | [Category], [] | [string]],
    Array<Listing>
  >,
  'schema' : ActorMethod<[], string>,
  'updateListing' : ActorMethod<
    [bigint, string, Category, bigint, string, Array<string>],
    Result
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];