/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'equipment' : IDL.Null,
  'bbGun' : IDL.Null,
});
export const Listing = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'seller' : IDL.Principal,
  'sellerName' : IDL.Text,
  'updatedAt' : IDL.Int,
  'category' : Category,
  'price' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});
export const ListingError = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'notFound' : IDL.Nat,
});
export const Result = IDL.Variant({ 'ok' : Listing, 'err' : ListingError });
export const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : ListingError });
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const SellerContact = IDL.Record({
  'seller' : IDL.Principal,
  'sellerName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_2], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createListing' : IDL.Func(
      [IDL.Text, Category, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [Result],
      [],
    ),
  'deleteListing' : IDL.Func([IDL.Nat], [Result_1], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getListing' : IDL.Func([IDL.Nat], [IDL.Opt(Listing)], ['query']),
  'getSellerContact' : IDL.Func([IDL.Nat], [IDL.Opt(SellerContact)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listListings' : IDL.Func(
      [IDL.Opt(Category), IDL.Opt(IDL.Text)],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'updateListing' : IDL.Func(
      [IDL.Nat, IDL.Text, Category, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({ 'equipment' : IDL.Null, 'bbGun' : IDL.Null });
  const Listing = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'seller' : IDL.Principal,
    'sellerName' : IDL.Text,
    'updatedAt' : IDL.Int,
    'category' : Category,
    'price' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  const ListingError = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'notFound' : IDL.Nat,
  });
  const Result = IDL.Variant({ 'ok' : Listing, 'err' : ListingError });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : ListingError });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const SellerContact = IDL.Record({
    'seller' : IDL.Principal,
    'sellerName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_2], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createListing' : IDL.Func(
        [IDL.Text, Category, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [Result],
        [],
      ),
    'deleteListing' : IDL.Func([IDL.Nat], [Result_1], []),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getListing' : IDL.Func([IDL.Nat], [IDL.Opt(Listing)], ['query']),
    'getSellerContact' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(SellerContact)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listListings' : IDL.Func(
        [IDL.Opt(Category), IDL.Opt(IDL.Text)],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'updateListing' : IDL.Func(
        [IDL.Nat, IDL.Text, Category, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };